spring:
  datasource:
    url: jdbc:h2:file:./db/H2/data;AUTO_SERVER=true
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true
logging:
  level:
    org.hibernate.SQL: info